spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mariadb://localhost:3310/team
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    properties:
      hibernate:
        format_sql: true

scheduler:
  scrap:
    youtube: "0 0/30 * * * *"
    weather: "0 0 0 * * *"


naver:
  geocoding:
    key: ${NAVER_API_KEY}
    Id: ${NAVER_CLIENT_ID}
    url: ${NAVER_API_URL}

