spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:company;DB_CLOSE_DELAY=-1
    username: root
    password:

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


scheduler:
  scrap:
    youtube: "0 0/30 * * * *"