spring:
  datasource:
    url: jdbc:mariadb://localhost:3310/team
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true


# 스케줄러 주기 변경을 위한 설정
scheduler:
  scrap:
    weather: "0 0 0 * * *"

