spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:mariadb://localhost:3310/team
    driver-class-name: org.mariadb.jdbc.Driver
    username: team_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: {port}
    username: {username}
    password: {password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  messages:
    basename: validation
    encoding: UTF-8
    properties:
      hibernate:
        auto_quote_keyword: true

  redis:
    port: {port}
    host: localhost

jwt:
  secret: {secret}
  refreshToken-validity-in-seconds: {refreshToken-validity-in-seconds}
  token-validity-in-seconds: {token-validity-in-seconds}

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: {password}


scheduler:
  scrap:
    youtube: "0 0/30 * * * *"
    weather: "0 0 0 * * *"


naver:
  geocoding:
    url: "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query="
    id: "gbgbgbgbgbg"
    key: "gbggbgbgb"

kakao:
  navigation:
    url: "https://apis-navi.kakaomobility.com/v1/directions?origin=%s&destination=%s&waypoints=&priority=RECOMMEND&car_fuel=GASOLINE&car_hipass=false&alternatives=false&road_details=false"
    key: "gbgbgbgb"