spring:
  profiles:
    include: oauth

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(n3ajWPr7jT9INxIxkA9jw+cHC3Mb+lofFJqlay4H8P0=)
    password: ENC(oxHwE1sp2Auc1doY2EqEFzmLEEaMmEMX0CLohpq6TeE=)
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  messages:
    basename: validation
    encoding: UTF-8
    properties:
      hibernate:
        auto_quote_keyword: true

  redis:
    port: 6379
    host: localhost

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  refreshToken-validity-in-seconds: 86400000
  token-validity-in-seconds: 1800000

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
    password: testpassword


scheduler:
  scrap:
    youtube: "0 0/30 * * * *"
    weather: "0 0 0 * * *"
    exchange: "0 0 0 * * *"


naver:
  geocoding:
    url: "https://naveropenapi.apigw.ntruss.com/map-geocode/v2/geocode?query="
    id: "gbgbgbgbgbg"
    key: "gbggbgbgb"

kakao:
  navigation:
    url: "https://apis-navi.kakaomobility.com/v1/directions?origin=%s&destination=%s&waypoints=&priority=RECOMMEND&car_fuel=GASOLINE&car_hipass=false&alternatives=false&road_details=false"
    key: "gbgbgbgb"