spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: {client-id}
            client-secret: {client-secret}
            scope: profile
            redirect-uri: {redirect-uri}
            client-name: google