spring:
  datasource:
    url: jdbc:mariadb://localhost:43306/lazier
    driver-class-name: org.mariadb.jdbc.Driver
    username: lazier_user
    password: 1234

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher