spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true

  messages:
    basename: validation
    encoding: UTF-8

    properties:
      hibernate:
        auto_quote_keyword: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hyelneu29@gmail.com
    password: hgdkhptmzwjlewxa
    properties:
      mail:
        smtp:
          starttls:
            enable: true

  redis:
    port: 6379
    host: 127.0.0.1

jwt:
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  refreshToken-validity-in-seconds: 86400
  token-validity-in-seconds: 1800

